/**
 * @description All default values for element types. These will be applied to new elements created via the construction function ONLY.
 * @see constructElementOfType() For creating new elements with default values.
 */
const defaults = {
    ER_ENTITY: {
        name: "Entity",
        kind: "ER_ENTITY",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 200,
        height: 50,
        type: "ER",
        state: 'normal',
        attributes: ['-attribute'],
        functions: ['+function'],
        canChangeTo: ["UML", "ER", "IE", "SD"],
        minWidth: 150,
        minHeight: 50,
    },
    ER_RELATION: {
        name: "Relation",
        kind: "ER_RELATION",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 90,
        height: 90,
        type: "ER",
        state: 'normal',
        canChangeTo: Object.values(relationType),
        minWidth: 60,
        minHeight: 60,
    },
    ER_ATTR: {
        name: "Attribute",
        kind: "ER_ATTR",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 90,
        height: 45,
        type: "ER",
        state: 'normal',
        minWidth: 90,
        minHeight: 45,
    },
    GHOST: {
        name: "GHOST",
        kind: "ER_ATTR",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 5,
        height: 5,
        type: "ER"
    },
    UML_ENTITY: {
        name: "Class",
        kind: "UML_ENTITY",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 200,
        height: 0, // Extra height when resizing larger than text.
        type: "UML",
        attributes: ['-Attribute'],
        functions: ['+Function'],
        canChangeTo: ["UML", "ER", "IE", "SD"],
        minWidth: 150,
        minHeight: 0,
    },
    UML_RELATION: {
        name: "Inheritance",
        kind: "UML_RELATION",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 60,
        height: 60,
        type: "UML",
        canChangeTo: Object.values(relationType),
        minWidth: 60,
        minHeight: 60,
    },
    IE_ENTITY: {
        name: "IE_ENTITY",
        kind: "IE_ENTITY",
        stroke: COLOR.BLACK,
        fill: COLOR.WHITE,
        width: 200,
        height: 0, // Extra height when resizing larger than text.
        type: "IE",
        primaryKey: ['*Primary Key'],
        attributes: ['-Attribute'],
        functions: ['+function'],
        canChangeTo: ["UML", "ER", "IE", "SD"],
        minWidth: 150,
        minHeight: 0,
    },
    IE_RELATION: {
        name: "Inheritance",
        kind: "IE_RELATION",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 50,
        height: 50,
        type: "IE",
        canChangeTo: Object.values(relationType),
        minWidth: 50,
        minHeight: 50,
    },
    SD_ENTITY: {
        name: "State",
        kind: "SD_ENTITY",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 200,
        height: 0, // Extra height when resizing larger than text.
        type: "SD",
        attributes: ['do: func'],
        functions: ['+function'],
        canChangeTo: ["UML", "ER", "IE", "SD"],
        minWidth: 150,
        minHeight: 0,
    },
    UML_INITIAL_STATE: {
        name: "UML Initial State",
        kind: "UML_INITIAL_STATE",
        fill: COLOR.BLACK,
        stroke: COLOR.BLACK,
        width: 60,
        height: 60,
        type: "SD",
        canChangeTo: null,
        minWidth: 60,
        minHeight: 60,
    },
    UML_FINAL_STATE: {
        name: "UML Final State",
        kind: "UML_FINAL_STATE",
        fill: COLOR.BLACK,
        stroke: COLOR.BLACK,
        width: 60,
        height: 60,
        type: "SD",
        canChangeTo: null,
        minWidth: 60,
        minHeight: 60,
    },
    UML_SUPER_STATE: {
        name: "UML Super State",
        kind: "UML_SUPER_STATE",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 500,
        height: 500,
        type: "SD",
        canChangeTo: null,
        minWidth: 200,
        minHeight: 150,
    },
    SEQUENCE_ACTOR: {
        name: "name",
        kind: "SEQUENCE_ACTOR",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 100,
        height: 500,
        type: "SE",
        canChangeTo: null,
        minWidth: 100,
        minHeight: 100,
    },
    SEQUENCE_OBJECT: {
        name: "name",
        kind: "SEQUENCE_OBJECT",
        fill: "#FFFFFF",
        stroke: "#000000",
        width: 100,
        height: 500,
        type: "SE",
        canChangeTo: null,
        minWidth: 100,
        minHeight: 50,
    },
    SEQUENCE_ACTIVATION: {
        name: "Activation",
        kind: "SEQUENCE_ACTIVATION",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 30,
        height: 100,
        type: "SE",
        canChangeTo: null,
        minWidth: 30,
        minHeight: 50,
    },
    SEQUENCE_LOOP_OR_ALT: {
        kind: "SEQUENCE_LOOP_OR_ALT",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 750,
        height: 300,
        type: "SE",
        alternatives: ["alternative1"],
        altOrLoop: "Alt",
        canChangeTo: null,
        minWidth: 150,
        minHeight: 50,
    },
    NOTE: {
        name: "NOTE",
        kind: "NOTE",
        fill: COLOR.WHITE,
        stroke: COLOR.BLACK,
        width: 200,
        height: 50,
        type: "NOTE",
        attributes: ['NOTE'],
        minWidth: 150,
        minHeight: 50,
    },
};

const defaultLine = {kind: "Normal"};
